settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from csk.views import (
    MainView,
    UserCallView,
    AdminCallView,
    adminpage,
    dashbord,
    profile,
    profile_master,
    
)
from auths.views import (
    LoginViewa,
    RegistrationView,
    LogoutView,
    
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainView,),
    path("reg/",RegistrationView.as_view()),
    path("login/",LoginViewa.as_view() ),
    path("logout/",LogoutView.as_view() ),
    path('usercalls/edit/<int:pk>', AdminCallView.as_view(), name='usercalls_edit'),

    path("adminpage/",adminpage,),
    path("callform/",UserCallView.as_view() ),
    # path("callform/",UserCallView),
    path("home/", dashbord),
    # path("profile/", profile),
    path("customer/<str:user_ptr_id>/", profile, name='customer'),
    path("master/<str:user_ptr_id>/", profile_master, name='master'),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/csk/models.py
from django.db import models

from auths.models import CustomUser
from multiselectfield import MultiSelectField
from django.core.validators import (
    MaxValueValidator,
    MinValueValidator,
)


class ServiceType(models.IntegerChoices):
    ELECTRIC = 1, 'Электрик'
    SANTECHNIK = 2, 'Сантехник'
    INZHENER = 3, 'Инженер'
    ZHIL_KOMM_SLUJBA = 4, 'Жилые и коммунальные службы'
    ARCHITECTOR_DESIGNER = 5, 'Архитектор/Дизайнер'
    YURIST = 6, 'Юрист'
    OTHER = 7, 'Прочее'


# class Service(models.Model):
#     service_points = models.IntegerField(default=ServiceType.OTHER, choices=ServiceType.choices)


class StatusType(models.IntegerChoices):
    EMERGENCY = 1, 'Срочный запрос'
    IN_PROCESS = 2, 'Запрос в процессе'
    DONE = 3, 'Запрос осуществлен'
    DECLINED = 4, 'Запрос отклонен'


# class Status(models.Model):
#     status_points = models.IntegerField(default=StatusType.IN_PROCESS, choices=StatusType.choices)


class UserCall(models.Model):
    """Call model for Users."""

    caller = models.ForeignKey(
        CustomUser,
        on_delete=models.CASCADE,
        verbose_name='заказчик'
    )
    personal_account = models.CharField(
        max_length=12, 
        verbose_name="лицевой счёт"
    )
    problem = models.TextField(
        verbose_name='причина обращения'
    )
    master_id = models.ForeignKey(
        'MasterUser',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='master_id'
    )
    datetime_created = models.DateTimeField(
        verbose_name="время создание",
        auto_now_add=True
    )
    status_points = models.IntegerField(default=StatusType.IN_PROCESS, choices=StatusType.choices)

    service_points = models.IntegerField(default=ServiceType.OTHER, choices=ServiceType.choices)

    class Meta:
        ordering = ('-datetime_created',)
        verbose_name = 'обращение'
        verbose_name_plural = 'обращения'


# class AdminCall(models.Model):
#     """Call model for Admin."""

#     user_call = models.ForeignKey(
#         UserCall,
#         on_delete=models.CASCADE
#     )
#     service_type = models.ForeignKey(
#         'Service',
#         on_delete=models.CASCADE
#     )

#     class Meta:
#         ordering = ('-datetime_created',)
#         verbose_name = 'обращение'
#         verbose_name_plural = 'обращения'




class MasterUser(CustomUser):
    SERVICE_CHOICES = (
        ('электрик', 'Электрик'),
        ('сантехник', 'Сантехник'),
        ('инженер', 'Инженер'),
        ('жилые и коммунальные службы', 'Жилые и коммунальные службы'),
        ('архитектор/дизайнер', 'Архитектор/Дизайнер'),
        ('юрист', 'Юрист'),
        ('прочее', 'Прочее'),
        
        # ... other choices
    )

    service_master = MultiSelectField(choices=SERVICE_CHOICES, validators=[MaxValueValidator(10)])
    avg_rating = models.FloatField(
        default=0.0,
        validators=[MinValueValidator(0.0), MaxValueValidator(5.0)],
    )

    ratings = models.ManyToManyField(
        'Rating',
        through='MasterUserRating',
        through_fields=('master_user', 'rating')
    )

    is_busy = models.BooleanField(
        default=False
    )

    class Meta:
        ordering = ('-datetime_created',)
        verbose_name = 'мастер'
        verbose_name_plural = 'мастера'


class RatingType(models.IntegerChoices):
    VERY_LOW = 1, 'Очень низко'
    LOW = 2, 'Низко'
    MID = 3, 'Средне'
    GOOD = 4, 'Хорошо'
    GREAT = 5, 'Прекрасно'

    
class Rating(models.Model):
    rating_points = models.IntegerField(default=RatingType.VERY_LOW, choices=RatingType.choices)


class MasterUserRating(models.Model):
    master_user = models.ForeignKey(
        MasterUser,
        on_delete=models.CASCADE
    )
    rating = models.ForeignKey(
        Rating,
        on_delete=models.CASCADE
    )

    

apps/csk/forms.py
from django import forms 

from .models import (
    UserCall,
)


class UserCallForm(forms.ModelForm):
    """UserCall form."""

   
        
    class Meta:
        abstract = True
        model = UserCall
        exclude = ('master_id', 'caller', 'service', 'status',)
        widgets = {
            'personal_account': forms.NumberInput(attrs={'id': 'personal_account', 'class': 'form-control'}),
            'problem': forms.Textarea(attrs={'id': 'problem', 'class': 'form-control'}),
        }


class UserCallUpdateForm(forms.ModelForm):
    """UserCallUpdate form."""

    class Meta:
        model = UserCall
        fields = "__all__"

        

class UserCallForm2(forms.ModelForm):
    """UserCall form."""

   
        
    class Meta:
        abstract = True
        model = UserCall
        fields = ("personal_account", "problem",)
        widgets = {
            'personal_account': forms.NumberInput(attrs={'id': 'personal_account', 'class': 'form-control'}),
            'problem': forms.Textarea(attrs={'id': 'problem', 'class': 'form-control'}),
        }

class MasterUpdateForm(forms.ModelForm):
    """"""

    class Metf:
        model = UserCall
        fields = ('status',)

apps/csk/views.py
# Python
from typing import Any
from urllib import request

# Django
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,redirect
from django.db.models import QuerySet
from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password
from django.http import (
    HttpRequest,
    HttpResponse,
    QueryDict,
)
from django.views.generic import (
    View,
    ListView,
)

from django.views.generic.edit import UpdateView

from django.core.files.uploadedfile import InMemoryUploadedFile

from auths.models import CustomUser


# Local
from .models import (
    UserCall,
    MasterUser
)
from .forms import (
    MasterUpdateForm,
    UserCallForm,
    UserCallUpdateForm,
    UserCallForm2
)
from abstracts.mixins import HttpResponseMixin
from .forms import (
    UserCallForm,
)

def MainView(request:HttpRequest):
    # orders=Order.objects.all()
    customers=CustomUser.objects.all()
    masters=MasterUser.objects.all()
    context={"ctx_user":request.user,"customers":customers,"masters":masters,}
    return render(request,'home_page.html', context )
# class MainView(HttpResponseMixin, View):
#     """Main view."""

#     def get(self, request: HttpRequest, *args, **kwargs):
#         customers=CustomUser.objects.all(),
#         print("dddddddddddddddddddddddddd",customers)
#         return render(
            
#             request=request,
#             template_name='home_page.html',
#             context={
                
#                 'ctx_user': request.user
#             }
#         )
    
# @login_required
# def UserCallView(request):
#     if request.method == 'POST':
#         form = UserCallForm(request.POST)
#         if form.is_valid():
            
#             order = form.save(commit=False)
#             order.caller = request.user
#             order.save()
#             return redirect('/')
            
#     else:
#         form = UserCallForm()
#     return render(request, 'main/callform.html', {'ctx_form': form})
class UserCallView(HttpResponseMixin,View):
    """View for UserCall."""
    
    form = UserCallForm

    def get(self, request: HttpRequest, *args: tuple, **kwargs: dict):
        return self.get_http_response(
            request=request,
            template_name='main/callform.html',
            context={
                'ctx_form' : self.form()
            }
        )

    def post(self, request,*args: tuple,  **kwargs: dict):
        if request.method == 'POST':
            print("sdfsdfsdfs", request.POST)
            form = UserCallForm2(request.POST)
            if form.is_valid():
                print("8888888888888888888888888888888888888888888888888")
                order = form.save(commit=False)
                order.caller = request.user
                order.save()
                return redirect('/')
            else:
                print(form.errors)
                return self.get_http_response(
                    request=request,
                    template_name='main/callform.html',
                    context={
                        'ctx_form' : form
                    }
                )


class AdminCallView(UpdateView):
    """Admin redact calls."""

    template_name = "admin/usercall_edit.html"
    model = UserCall
    form_class = UserCallUpdateForm

    def get_success_url(self):
        return "/callform/"
    
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        masterr = MasterUser.objects.get(id=request.POST.get('caller'))
        masterr.is_busy = True
        masterr.save()
        return super(AdminCallView,self).post(request, *args, **kwargs)


def adminpage(request):
    callforms=UserCall.objects.all()
    # customers=CustomUser.objects.all()
    context={"callforms":callforms,}
    return render(request,'admin/adminpage.html', context )  



def dashbord(request):
    return render(request, 'dashbord/dashbord_main.html')

# def profile(request):
#     return render(request, "profile_user/profile.html")


# def profile(request):
    # customer=CustomUser.objects.get(id=user_ptr_id)
    # orders = customer.order_set.all()
    # users_call = customer.usercall_set.all()

    # context = {"customer":customer, "orders":users_call,}
    # return render(request,'profile_user/profile.html')
    caller = CustomUser.objects.get(id=form['caller'].value())
def profile(request,user_ptr_id):
    customer=CustomUser.objects.get(id=user_ptr_id)
    # orders = customer.order_set.all()
    users_call = customer.usercall_set.all()

    context = {"customer":customer, "orders":users_call,}
    return render(request,'profile_user/profile.html', context )


def profile_master(request,user_ptr_id):
    customer=MasterUser.objects.get(id=user_ptr_id)
    # orders = customer.order_set.all()
    users_call = UserCall.objects.filter(master_id=customer)

    context = {"master":customer, "users_calls":users_call,}
    return render(request,'profile_user/profile_master.html', context )
class MasterUpdateView(UpdateView):

    template_name = ""
    model = UserCall
    form_class = MasterUpdateForm

    def get_success_url(self):
        return "/"

apps/csk/templates/profile_user/profile.html
{% extends 'home_page.html' %}

{% block content %}


<!DOCTYPE html>
<body>
    <div class="container">
        <div class="card">
            <div class="card-body">

                <div class="row">
                    <div class="col-4 user">
                            
                        <img class="rounded-circle" alt="avatar1" src="https://mdbcdn.b-cdn.net/img/new/avatars/9.webp" />
                        <h6>  ФИО: {{customer.full_name}} </h6>
                    </div>
                    <div class="col-sm-8 status">
                        <div class="text-left">
                            
                        </div>
                    </div>

                </div>
                <hr>
                <div></div>
                <div class="col-md-7">
                    <h5>Ваши заказы</h5>
                    <hr>
                    <div class="card card-body">
                        {%comment%} <a class="btn-primary btn-sm btn-blcok"  href="{% url 'order_form'%}">Создать услугу</a> {%endcomment%}
                        <div class="table-responsive">
                        <table class="table">
                            <tr>
                                <th>Лицевой Счёт</th>
                                <th>Статус</th>
                                <th>Причина обращения</th>
                                <th>Тип услуги</th>
                                <th>Мастер</th>
                            </tr>
                            {% for order in masters %}
                                <tr>
                                    <td> {{order.personal_account}}</td>
                                    <td> {{order.get_status_points_display}} </td>
                                    <td> {{order.problem}}</td>
                                    <td> {{user_call.get_service_points_display}} </td>
                                    <td> {{user_call.get_,master_id}} </td>
                                    {%comment%}<td>{{orders.status}}</td>
                                    <td><a href="{% url 'update_order' order.id %}">Обновить</a></td>
                                    <td><a href="{% url 'delete_order' order.id %}">Удалить</a></td>{%endcomment%}
                                </tr>
                            {% endfor %}
            
                        </table>
                    </div>
                </div>
                </div>


            </div>
        </div>
        

        
    </div>
    


</body>



{% endblock content %}

apps/csk/templates/profile_user/profile_master.html
{% extends 'home_page.html' %}

{% block content %}


<!DOCTYPE html>
<body>
    <div class="container">
        <div class="card">
            <div class="card-body">

                <div class="row">
                    <div class="col-4 user">
                        
                        <img class="rounded-circle" alt="avatar1" src="https://mdbcdn.b-cdn.net/img/new/avatars/9.webp" />
                        <h6>  ФИО: {{master.full_name}} </h6>
                    </div>
                    <div class="col-sm-8 status">
                        <div class="text-left">
                            <h6>Контакты {{master.phone_number}}</h6>
                        </div>
                    </div>
                
                </div>
                <hr>
                <div></div>
                <div class="col-md-7">
                    <h5>Начначенные заказы</h5>
                    <hr>
                    <div class="card card-body">
                        {%comment%} <a class="btn-primary btn-sm btn-blcok"  href="{% url 'order_form'%}">Создать услугу</a> {%endcomment%}
                        <div class="table-responsive">
                        <table class="table">
                            <tr>
                                <th>Лицевой Счёт</th>
                                <th>Статус</th>
                                <th>Тип услуги</th>
                                
                            </tr>
                            {% for user_call in users_calls %}
                                <tr>
                                    <td> {{user_call.personal_account}}</td>
                                    <td> {{user_call.get_status_points_display}} </td>
                                    <td> {{user_call.get_service_points_display}} </td>
                                    {%comment%}<td>{{orders.status}}</td>
                                    <td><a href="{% url 'update_order' order.id %}">Обновить</a></td>
                                    <td><a href="{% url 'delete_order' order.id %}">Удалить</a></td>{%endcomment%}
                                </tr>
                            {% endfor %}
            
                        </table>
                    </div>
                </div>
                </div>


            </div>
        </div>
        

        
    </div>
    


</body>



{% endblock content %}